language: d

d:
  - dmd-2.072.0
  - dmd-2.071.1
  - dmd-2.070.1
  - dmd-2.069.2
  - ldc-1.0.0
  - gdc-4.9.2

install:

script:
  - dub test --compiler=${DC}

branches:
  only:
    - master

notifications:
  email: true

sudo: false

matrix:
  exclude:
    - d: gdc-4.9.2
