language: d
sudo: false

addons:
  apt:
    packages:
      - libevent-dev

d:
  - dmd-2.076.0
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2
  - ldc-1.3.0
  - ldc-1.2.0
  - ldc-1.1.1

install:

script:
  - dub upgrade && dub test --compiler=${DC}

branches:
  only:
    - master

notifications:
  email: true

sudo: false
