language: d
sudo: false

d:
  - dmd-2.073.0
  - dmd-2.072.2
  - ldc-1.0.0
  - ldc-1.1.0
  - gdc-4.9.2
  - dmd-2.071.2
  - dmd-2.070.2

install:

script:
  - dub upgrade && dub test --compiler=${DC}

branches:
  only:
    - master

notifications:
  email: true

sudo: false

matrix:
  exclude:
    - d: gdc-4.9.2
