language: d
sudo: false

addons:
  apt:
    packages:
      - libevent-dev

d:
  - dmd-2.081.1
  - dmd-2.080.1
  - dmd-2.079.1
  - dmd-2.078.3
  - dmd-2.077.1
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2
  - ldc-1.10.0
  - ldc-1.9.0
  - ldc-1.8.0
  - ldc-1.7.0
  - ldc-1.6.0
  - ldc-1.5.0
  - ldc-1.4.0
  - ldc-1.3.0
  - ldc-1.2.0

install:

script:
  - dub upgrade && dub test --compiler=${DC}

branches:
  only:
    - master

notifications:
  email: true

sudo: false
